accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('create/', views.create_account, name='create')
]

alatool/urls.py
from django.urls import path
from . import views

app_name = 'alatool'
urlpatterns = [
    path('top/', views.top, name='top'),
    path('info/', views.info, name='info'),
    path('register/', views.register, name='register'),
    path('history/', views.history, name='history'),
    path('detail/<int:sample_id>', views.detail, name='detail'),
    path('edit/<int:sample_id>', views.edit, name='edit'),
    path('delete/<int:sample_id>', views.delete, name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.forms import UserCreationForm


class LoginForm(AuthenticationForm):
    """ログオンフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label



class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.views.generic import CreateView
from . forms import UserCreateForm

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'accounts/login.html'


#アカウント作成
class Create_account(CreateView):
    def post(self, request, *args, **kwargs):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            #フォームから'username'を読み取る
            username = form.cleaned_data.get('username')
            #フォームから'password1'を読み取る
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        return render(request, 'accounts/create.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        return  render(request, 'accounts/create.html', {'form': form,})

create_account = Create_account.as_view()

templates/accounts/create.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cccabinet.jpn.org/bootstrap4/css/style.css">
    <title>ちょっと「ぶんせき」した気になれるツール</title>
  </head>

  <body>
    <div class="container">
      <div id="create-row" class="row justify-content-center align-items-center" style="height:100vh">
        <div id="create-column" class="col-md-6 border boredr-info rounded">
          <div id="create-box" class="col-md-12">
            <h6 class="text-center text-info">ユーザー登録</h6>

              <form method="POST" action="{% url 'accounts:create' %}">
                <div class="form-group text-info">
                {% csrf_token %}
                <label>ユーザーID</label>
                {{ form.username }}
                {{ form.username.errors }}
                <label>パスワード</label>
                {{ form.password1 }}
                {{ form.password1.errors }}
                <label>パスワード(確認)</label>
                {{ form.password2 }}
                {{ form.password2.errors }}
                </div>
                <div class="form-group">
                  <input type="submit" name="submit" class="btn btn-info btn-md" value="登録">
                </div>
              </form>


          </div>  
        </div>
      </div>
    </div>
  </body>
</html>

templates/accounts/login.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% load static %}

<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cccabinet.jpn.org/bootstrap4/css/style.css">
  <title>ちょっと「ぶんせき」した気になれるツール</title>
</head>
<body>
  <div id="login">
      <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center" style="height:100vh">
            <div id="login-column" class="col-md-6 border boredr-info rounded">
                  <div id="login-box" class="col-md-12">
                    <form action="" method="POST">
                          <h6 class="text-center text-info">ちょっと「ぶんせき」した気になれるツール</h6>
                          <div class="form-group">
                              {% csrf_token %}
                              {% for field in form %}
                                <div class="form-group has-feedback">
                                  {{ field }}
                                </div>
                              {% endfor %}
                          </div>
                          {% for error in form.non_field_errors %}
                          <div class="alert alert-danger" role="alert">
                            <p>{{ error }}</p>
                          </div>
                          {% endfor %}
                          <div class="form-group">
                              <input type="submit" name="submit" class="btn btn-info btn-md" value="ログイン">
                                <a href="/create" class="text-info">登録はこちら</a>
                          </div>
                    </form>
                   </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</body>
</html>