alatool/urls.py
from django.urls import path
from . import views

app_name = 'alatool'
urlpatterns = [
    path('top/', views.top, name='top'),
    path('info/', views.info, name='info'),
    path('register/', views.register, name='register'),
    path('history/', views.history, name='history'),
    path('detail/<int:sample_id>', views.detail, name='detail'),
    path('edit/<int:sample_id>', views.edit, name='edit'),
    path('delete/<int:sample_id>', views.delete, name='delete'),
]

alatool/models.py
from django.db import models
from datetime import date

class MatchRecord(models.Model):
    class Meta:
        db_table = 'match_record' # DB内で使用するテーブル名
        verbose_name_plural = 'match_record' # Admionサイトで表示するテーブル名
    
    #勝敗
    WIN_LOSE_CHOICES = (
        (0, '勝利'),
        (1, '敗北'),
    )
    #先攻後攻
    FRIRST_STRIKE_CHOICES = (
        (0, '先攻'),
        (1, '後攻'),
    )
    #フリーor公式
    BATTLE_DIVISION_CHOICES = (
        (0, 'フリー'),
        (1, '公式'),
    )

    user_id = models.IntegerField('user_id', null=True, blank=False) # 数値を格納
    game_date = models.DateField ('game_date', default=date.today, null=True, blank=False) # 文字列を格納
    game_name = models.CharField('game_name', max_length=30, null=True, blank=False) # 文字列を格納
    battle_division = models.IntegerField('battle_division', choices = BATTLE_DIVISION_CHOICES, null=True, blank=False) # 数値
    my_title = models.CharField('my_title', max_length=50, null=True, blank=False) # 文字列を格納
    opp_title = models.CharField('opp_title', max_length=50, null=True, blank=False) # 文字列を格納
    frirst_strike = models.IntegerField('frirst_strike', choices = FRIRST_STRIKE_CHOICES, null=True, blank=False) # 数値
    win_lose = models.IntegerField('win_lose', choices = WIN_LOSE_CHOICES, null=True, blank=False) # 数値
    game_score = models.IntegerField('game_score', null=True, blank=True) # 数値
    comment = models.TextField('comment', max_length=255, null=True, blank=True) # 文字列を格納
    create_date = models.DateTimeField ('create_date', auto_now_add = True, null=True, blank=True) # 文字列を格納
    update_date = models.DateTimeField ('update_date', auto_now = True, null=True, blank=True) # 文字列を格納
    

alatool/forms.py
from django.forms import ModelForm
from .models import MatchRecord
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class TextAreaInput(forms.DateInput):
    input_type = 'textarea'

class SampleForm(ModelForm):
    class Meta:
        model = MatchRecord
        fields = [
                'game_name',
                'game_date',
                'my_title',
                'opp_title',
                'win_lose',
                'comment',
                'frirst_strike',
                'battle_division'
        ]
        
        widgets = {
                'game_date': DateInput(),
                'comment':forms.Textarea(attrs={'rows':4,})
        }

alatool/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View  
from .models import MatchRecord
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SampleForm
from django.views.decorators.http import require_POST

#リスト用
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q #追加


class AlaTop(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        #ユーザIDを取得
        user = self.request.user.id
        #初期表示用
        trg_date = date.today()
        trg_year = trg_date.strftime("%Y")
        trg_month = trg_date.strftime("%#m")
        result = MatchRecord.objects.filter(user_id = user,
                                         game_date__year__gte = trg_year,
                                         game_date__month__range = (trg_month,trg_month)
                                         ).order_by("opp_title")

        ###初期表示円グラフ用###
        #相手別対戦回数集計
        #タイトル別の勝ち数と負け数を辞書で作る
        win_dict,lose_dict,total_dict = {},{},{}
        win_cnt,lose_cnt = 0,0
        cur_title = ''

        for obj in result:
            #タイトルが変わったらリセットする
            if cur_title != obj.opp_title:
                cur_title = obj.opp_title
                win_cnt,lose_cnt = 0,0
                #一方が0の可能性を考慮して{"タイトル":0}を設定
                win_dict[cur_title] = win_cnt
                lose_dict[cur_title] = lose_cnt
            if obj.win_lose == 0:
                win_cnt += 1
                win_dict[cur_title] = win_cnt
            elif obj.win_lose == 1:
                lose_cnt += 1
                lose_dict[cur_title] = lose_cnt
            total_dict[cur_title] = win_cnt + lose_cnt
            
            #更新があったか判定

        '''
        if obj.create_date == obj.update_date:
            print("更新なし",obj.create_date,obj.update_date)
        else:
            print("更新あり",obj.create_date,obj.update_date)
        '''

        #グラフ用情報集計
        #トータルカウントを降順に修正(対戦数の多い順)
        new_total_dict = sorted(total_dict.items(),key = lambda x:x[1],reverse=True)
        
        pie_labels,pie_data,bar_data = [],[],[]
        win_cnt,lose_cnt = 0,0
        for k,v in new_total_dict:
            #タイトル作成
            pie_labels.append(k)
            #タイトル別対戦数
            pie_data.append(win_dict[k] + lose_dict[k])
            #タイトル別勝率
            bar_data.append(WinRate(total = v,win = win_dict[k],option = 0))
            #当月勝数
            win_cnt += win_dict[k]

        total_cnt = sum(pie_data)
        lose_cnt = total_cnt - win_cnt
        win_rate = WinRate(total = total_cnt,win = win_cnt,option = 1)
        
        ###初期表示折れ線グラフ用###
        context = {'trg_month':(trg_year + '年' + trg_month + '月'),
                    'total_cnt':total_cnt,
                    'win_cnt':win_cnt,
                    'lose_cnt':lose_cnt,
                    'win_rate':win_rate,
                    'pie_labels':pie_labels,
                    'pie_data':pie_data,
                    'bar_data':bar_data
                    }
        return render(request, 'alatool/top.html', context=context,)

top = AlaTop.as_view()

class AlaInfo(LoginRequiredMixin,View):  
    def get(self, request, *args, **kwargs):
        return render(request, 'alatool/info.html')

info = AlaInfo.as_view()

'''
class AlaRegister(LoginRequiredMixin,View):  
    def get(self, request, *args, **kwargs):
        return render(request, 'alatool/register.html')

    def post(self, request, *args, **kwargs):
        #登録処理
        input_userid = self.request.user.id
        input_game_date = request.POST['input_game_date']
        input_game_name = request.POST['input_game_name']
        input_my_title = request.POST['input_my_title']
        input_opp_title = request.POST['input_opp_title']
        input_win_lose = request.POST['input_win_lose']
        input_comment = request.POST['input_comment']
        input_frirst_strike = request.POST['input_frirst_strike']
        input_battle_division = request.POST['input_battle_division']
        data = MatchRecord( user_id = input_userid,
                         game_date = input_game_date,
                         game_name = input_game_name,
                         my_title = input_my_title,
                         opp_title = input_opp_title,
                         win_lose = input_win_lose,
                         comment = input_comment,
                         frirst_strike = input_frirst_strike,
                         battle_division = input_battle_division)
        data.save()
        return render(request, 'alatool/register.html')

register = AlaRegister.as_view()
'''

#履歴表示
class AlaHistory(LoginRequiredMixin,View):  
    def get(self, request, *args, **kwargs):

        input_userid = self.request.user.id
        querySet = {}
        querySet["user_id"] = input_userid

        result = MatchRecord.objects.filter(**querySet).order_by("game_date").reverse()
        #0 or 1のcolumnは出力前に変換する
        for i,v in enumerate(result):
            if result[i].win_lose == 0:result[i].win_lose = '勝利'
            elif result[i].win_lose == 1:result[i].win_lose = '敗北'
            if result[i].frirst_strike == 0:result[i].frirst_strike = '先攻'
            elif result[i].frirst_strike == 1:result[i].frirst_strike = '後攻'
            elif result[i].frirst_strike is None:result[i].frirst_strike = ''
            if result[i].battle_division == 0:result[i].battle_division = 'フリー'
            elif result[i].battle_division == 1:result[i].battle_division = '公式'
            if result[i].comment is None:result[i].comment = ''

        page_obj = paginate_query(request, result, 10)   # ページネーション
        context={"result_obj":page_obj}

        return render(request, 'alatool/history.html', context=context)

history = AlaHistory.as_view()

def WinRate(total,win,option):
    '''勝率を計算する(勝利数/対戦数)
       optionによって”%”付きか数値か分ける[0:%無し,1:%有り]
       total:int
       win:int
       return:0 == float, 1 == str
    '''
    if total == 0 or win == 0:
        if option == 0:
            win_rate = round((0)*100,1)
        elif option == 1:
            win_rate = '{:.1%}'.format(0)
    else:
        if option == 0:
            win_rate = round((win/total)*100,1)
        elif option == 1:
            win_rate = '{:.1%}'.format(win / total)
    return win_rate



# ページネーション用に、Pageオブジェクトを返す。
def paginate_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')

    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    

    return page_obj

#詳細表示用
def detail(request, sample_id):
    #DBからキーユーザIDと合致するレコードを取得する
    result = MatchRecord.objects.get(id=sample_id)
    #DBからキーユーザIDと合致するレコードを取得する
    if result.win_lose == 0:result.win_lose = '勝利'
    elif result.win_lose == 1:result.win_lose = '敗北'
    if result.frirst_strike == 0:result.frirst_strike = '先攻'
    elif result.frirst_strike == 1:result.frirst_strike = '後攻'
    elif result.frirst_strike is None:result.frirst_strike = ''
    if result.battle_division == 0:result.battle_division = 'フリー'
    elif result.battle_division == 1:result.battle_division = '公式'
    if result.comment is None:result.comment = ''

    context = {'result':result,}
    return render(request, 'alatool/detail.html', context=context)

#編集用
def edit(request, sample_id):
    sampleDB = get_object_or_404(MatchRecord, id=sample_id)
    #POSTで受け取った場合、値を引き継いで表示
    if request.method == "POST":
        form = SampleForm(request.POST, instance=sampleDB)
        if form.is_valid():
            form.save()
            return redirect('alatool:history')
    else:
        form = SampleForm(instance=sampleDB)
    return render(request, 'alatool/edit.html', {'form': form, 'result':sampleDB })

#削除用POSTの時だけ発火
@require_POST
def delete(request, sample_id):
    sampleDB = get_object_or_404(MatchRecord, id=sample_id)
    sampleDB.delete()
    return redirect('alatool:history')

def register(request):
    if request.method == "POST":
        form = SampleForm(request.POST)
        if form.is_valid():
            tempDB = form.save(commit = False)
            tempDB.user_id = request.user.id
            tempDB.save()
            return redirect('alatool:register')
    else:
        #登録画面初期表示
        defautt_data = {
            'game_date':date.today(),
            'game_name':'WS',
            'battle_division':0,
            'frirst_strike':0,
            'win_lose':0,
            }
        form = SampleForm(defautt_data)
    return render(request, 'alatool/register.html', {'form': form})

templates/alatool/detail.html
{% extends 'base.html' %}
{% block contents %}

<!--詳細画面-->
<h4 class="mt-1 mb-4 border-bottom">詳細</h4>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <p>対戦ゲーム：{{result.game_name}}</p>
      <p>対戦日付：{{result.game_date}}</p>
      <p>試合区分：{{result.battle_division}}</p>
      <p>使用タイトル：{{result.my_title}}</p>
      <p>相手タイトル：{{result.opp_title}}</p>
      <p>先攻後攻：{{result.frirst_strike}}</p>
      <p>勝敗：{{result.win_lose}}</p>
      <p>コメント：{{result.comment}}</p>
    </div>
  </div>
  <div class="row pl-3">
    <a role="button" class="btn btn-primary" href="{% url 'alatool:edit' result.id %}">編集</a>
        <form method="post" action="{% url 'alatool:delete' result.id %}">{% csrf_token %}
          <button class="btn btn-warning ml-3" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
  </div>
  <p></p>
</div>
{% endblock %}

templates/alatool/edit.html
{% extends 'base.html' %}
{% block contents %}
{% load widget_tweaks %}

<!--編集画面-->
<h4 class="mt-1 mb-4 border-bottom">編集中…</h4>
<form action="{% url 'alatool:edit' result.id %}" method="POST">
<div class="container-fluid">
  <div class="row">
    <div class="col-auto">
      対戦日付
      {{ form.game_date|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      対戦ゲーム
      {{ form.game_name|add_class:'form-control' }}
      試合区分
      {{ form.battle_division|add_class:'form-control' }}
      使用タイトル
      {{ form.my_title|add_class:'form-control' }}
      相手タイトル
      {{ form.opp_title|add_class:'form-control' }}
      先攻後攻
      {{ form.frirst_strike|add_class:'form-control' }}
      勝敗
      {{ form.win_lose|add_class:'form-control' }}
      コメント
      {{ form.comment|add_class:'form-control' }}
      <p></p>
      <button type="submit" name="button" class="btn btn-primary">保存</button>
      <p></p>
    </div>
  </div>
</div>
{% csrf_token %}
</form>
{% endblock %}

templates/alatool/history.html
{% extends 'base.html' %}
{% block contents %}

<!--対戦履歴-->
<h4 class="mt-1 mb-4 border-bottom">対戦履歴</h4>
<div class="container-fluid"></div>
  <div class="row">
    <div class="col-12">
      <table class="table table-sm table-bordered table-responsive">
        <thead class="thead-dark">
        <tr>
          <th>日付</th>
          <th>区分</th>
          <th>デッキ(自)</th>
          <th>デッキ(相)</th>
          <th>先後</th>
          <th>勝敗</th>
          <th>コメント</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          {% for s in result_obj %}
          <tr>
            <td width="15%">{{ s.game_date }}</td>
            <td width="10%">{{ s.battle_division }}</td>
            <td width="15%">{{ s.my_title }}</td>
            <td width="15%">{{ s.opp_title }}</td>
            <td width="10%">{{ s.frirst_strike }}</td>
            <td width="10%">{{ s.win_lose }}</td>
            <td width="20%">{{ s.comment }}</td>
            <td><a href="{% url 'alatool:detail' s.id %}">詳細</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% include 'page.html' %}
    </div>      
  </div>
</div>
{% csrf_token %}


{% endblock %}

templates/alatool/info.html
{% extends 'base.html' %}
{% block contents %}

<!--information-->
<h4 class="mt-1 mb-4 border-bottom">考え中...</h4>
<div class="container-fluid">
  <div class="row">
    <div class="col-auto">
      <p>＜発売予定＞</p>
      <table class="table table-sm table-responsive">
        <thead class="thead-dark">
        <tr>
          <th>発売日</th>
          <th>区分</th>
          <th>タイトル</th>
        </tr>
        </thead>
        <tbody>
          <tr>
            <td>2020/10/30</td>
            <td>BS</td>
            <td>Summer Pockets REFLECTION BLUE</td>
          </tr>
          <tr>
            <td>2020/11/13</td>
            <td>TD</td>
            <td>痛いのは嫌なので防御力に極振りしたいと思います。</td>
          </tr>
          <tr>
            <td>2020/11/20</td>
            <td>BS</td>
            <td>痛いのは嫌なので防御力に極振りしたいと思います。</td>
          </tr>
          <tr>
            <td>2020/12/11</td>
            <td>TD</td>
            <td>ラブライブ！虹ヶ咲学園スクールアイドル同好会 feat.スクールアイドルフェスティバル ALL STARS</td>
          </tr>
          <tr>
            <td>2020/12/18</td>
            <td>TD,BS</td>
            <td>かぐや様は告らせたい～天才たちの恋愛頭脳戦～</td>
          </tr>
          <tr>
            <td>2020/12/25</td>
            <td>TD</td>
            <td>彼女、お借りします</td>
          </tr>
          <tr>
            <td>2020/12/25</td>
            <td>TD</td>
            <td>アニメ「プリンセスコネクト！Re:Dive」</td>
          </tr>
          <tr>
            <td>2021/1/8</td>
            <td>BS</td>
            <td>アニメ「プリンセスコネクト！Re:Dive」</td>
          </tr>
          <tr>
            <td>2021/1/22</td>
            <td>BS</td>
            <td>彼女、お借りします
          </tr>          
        </tbody>
      </table>




      <p>＜考え中…＞</p>
    </div>
  </div>
</div>
{% csrf_token %}
{% endblock %}

templates/alatool/register.html
{% extends 'base.html' %}
{% block contents %}
{% load widget_tweaks %}
{% load static %}

<!--登録画面-->
<h4 class="mt-1 mb-4 border-bottom">登録</h4>
<form action="{% url 'alatool:register' %}" method="POST">
<div class="container-fluid">
  <div class="row">
    <div class="col-auto">
      対戦日付
      {{ form.game_date|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      対戦ゲーム
      {{ form.game_name|add_class:'form-control' }}
      試合区分
      {{ form.battle_division|add_class:'form-control' }}
      使用タイトル
      {{ form.my_title|add_class:'form-control' }}
      相手タイトル
      {{ form.opp_title|add_class:'form-control' }}
      先攻後攻
      {{ form.frirst_strike|add_class:'form-control' }}
      勝敗
      {{ form.win_lose|add_class:'form-control' }}
      コメント
      {{ form.comment|add_class:'form-control' }}
      <p></p>
      <button type="submit" name="button" class="btn btn-success">登録</button>
      <p></p>
    </div>
  </div>
</div>
{% csrf_token %}
</form>

{% endblock %}

templates/alatool/top.html
{% extends 'base.html' %}
{% block contents %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-1 border-bottom">
    <h1 class="h2">『{{trg_month}}』の成績</h1>
</div>

<div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-10 mt-1">
          <p>{{total_cnt}}戦 {{win_cnt}}勝 {{lose_cnt}}敗：<span class="border-bottom">勝率{{win_rate}}</span></p>
        </div>
      </div>
    </div>
</div>

<div>
<canvas id="myPieChart"></canvas>
<br></br>
<canvas id="myBarChart"></canvas>
<br></br>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  <script type="text/javascript">
    //chart.jsプラグイン
    Chart.plugins.register({
        afterDatasetsDraw: function (chart, easing) {
            // To only draw at the end of animation, check for easing === 1
            var ctx = chart.ctx;

            chart.data.datasets.forEach(function (dataset, i) {
                var meta = chart.getDatasetMeta(i);
                if (!meta.hidden) {
                    meta.data.forEach(function (element, index) {
                        // Draw the text in black, with the specified font
                        ctx.fillStyle = 'rgb(0, 0, 0)';

                        var fontSize = 10;
                        var fontStyle = 'normal';
                        var fontFamily = 'Helvetica Neue';
                        ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

                        // Just naively convert to string for now
                        var dataString = dataset.data[index].toString();

                        // Make sure alignment settings are correct
                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'middle';

                        var padding = 0;
                        var position = element.tooltipPosition();
                        ctx.fillText(dataString, position.x, position.y - (fontSize / 2) - padding);
                    });
                }
            });
        }
    });


    //Viewからグラフの入力値を受け取る
    {% autoescape off %}
    var labels = {{pie_labels}}
    {% endautoescape %}
    var piedata = {{pie_data}}

    var ctx = document.getElementById("myPieChart");
    var myPieChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: labels,
        datasets: [{
            backgroundColor: ["#BB5179","#FAFF67","#58A27C","#1e90ff","#ee82ee","#f4a460","#90ee90"],
            data: piedata
        }]
      },
      options: {
        responsive:true,
        title: {
          display: true,
          text: '対戦相手内訳(対戦数)'
        }
      }
    });

    var bardata = {{bar_data}}
    var ctx = document.getElementById("myBarChart");
    var myBarChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [
          {
            label: 'TOTAL',data: bardata,backgroundColor: "#56ffff"
          }
        ]
      },
      options: {
        responsive:true,
        title: {
          display: true,
          text: '対戦相手別勝率'
        },
        scales: {
          yAxes: [{
            ticks: {
              suggestedMax: 100,
              suggestedMin: 0,
              stepSize: 25,
              callback: function(value, index, values){
                return  value +  '%'
              }
            }
          }]
        },
      }
    });
    </script>
</div>
{% endblock %}